site_name: Arango ORM
site_url: https://arango-orm.readthedocs.io/en/latest/
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Collections: collections.md
  - Collection Inheritance: collection-inheritance.md
  - Referenced Objects: referenced-objects.md
  - Events: events.md
  - Graphs: graphs.md
  - API Reference: reference.md
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings